name: my_case
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #core packages
  cupertino_icons: ^1.0.2
  go_router: ^14.1.2
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.3.4
  shared_preferences: ^2.2.3
  bot_toast: ^4.0.3
  package_info_plus: any
  settings_ui: ^2.0.2
  skeletons: ^0.0.3
  flex_color_scheme: ^7.3.1
  in_app_update: ^4.2.2
  dio: ^5.0.0
  pretty_dio_logger: ^1.3.1
  flutter_i18n: ^0.35.1
  riverpod_generator: ^2.2.2
  riverpod_annotation: ^2.3.3
  get_it: ^7.7.0
  slang: ^3.30.1
  slang_flutter: ^3.30.0
  styled_text: ^8.1.0
  youtube_player_flutter: ^9.0.1
  video_player: ^2.8.6
  url_launcher: ^6.2.6
  flutter_chat_ui: ^1.6.13
  percent_indicator: ^4.2.3
  flutter_easyloading: ^3.0.5
  formz: ^0.7.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_sound: ^9.6.0
  record: ^5.1.2
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  flutter_launcher_icons: "^0.13.1"



flutter:
  uses-material-design: true
  assets:
    - assets/images/
