name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v3
      with:
        flutter-version: '3.22.2'

    - name: Install dependencies
      run: |
        cd my_case; flutter pub get

    - name: Run linting
      run: |
        flutter analyze

    - name: Build Flutter app
      run: |
        cd my_case; 
        flutter build apk --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flutter-build
        path: build/app/outputs/flutter-apk/release/app-release.apk
